### ISSUE TITLE
Meaningless error messages

### ISSUE THREAD

**Issue by spacefrogg** [Vladimir-csp/uwsm#71]
I was trying uwsm-20.4 (via Nix home-manager) on Ubuntu 24.05 and preparation of the window manager environment fails with the following error (with DEBUG):

```
Nov 26 22:02:03 uwsm_env-preloader[95612]: [Errno 25] Inappropriate ioctl for device
Nov 26 22:02:03 uwsm_env-preloader[95612]: Traceback (most recent call last):
Nov 26 22:02:03 uwsm_env-preloader[95612]:   File "/nix/store/jdw6vbgkwa2ah41m78jskqjh6qbkcryd-uwsm-0.20.4/share/uwsm/modules/uwsm/main.py", line 4817, in main
Nov 26 22:02:03 uwsm_env-preloader[95612]:     prepare_env()
Nov 26 22:02:03 uwsm_env-preloader[95612]:   File "/nix/store/jdw6vbgkwa2ah41m78jskqjh6qbkcryd-uwsm-0.20.4/share/uwsm/modules/uwsm/main.py", line 2854, in prepare_env
Nov 26 22:02:03 uwsm_env-preloader[95612]:     session_id = get_session_by_vt(v_term)
Nov 26 22:02:03 uwsm_env-preloader[95612]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 26 22:02:03 uwsm_env-preloader[95612]:   File "/nix/store/jdw6vbgkwa2ah41m78jskqjh6qbkcryd-uwsm-0.20.4/share/uwsm/modules/uwsm/main.py", line 2578, in get_session_by_vt
Nov 26 22:02:03 uwsm_env-preloader[95612]:     if int(vtnr) == v_term and user == os.getlogin():
Nov 26 22:02:03 uwsm_env-preloader[95612]:                                        ^^^^^^^^^^^^^
Nov 26 22:02:03 uwsm_env-preloader[95612]: OSError: [Errno 25] Inappropriate ioctl for device
Nov 26 22:02:03 uwsm_env-preloader[95612]: Cleaning up...
```

I realised that this has to do with the corporate environment that I am in. User names are resolved via an external library (via nsswitch) which programs coming from Nix fail to load. (I fixed that with `LD_PRELOAD`). Now to my actual issue:

Both, mishandling `DEBUG` (I didn't initially realise that it has to be an int) and this error just throw back traces or meaningless messages instead of "DEBUG must be a number" or "Could not determine user name". And now, that I look at it, `int(vtnr)` looks suspiciously unchecked as well. ;-)

**Comment by Vladimir-csp** [comment]
This was handled by acf7994, 734c9476 and logging/printing changes. Feel free to reopen if you spot anything else.
